/*
 * Assertio - Assertion library API
 * Distributed assertion library
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.assertio.client.api;

import io.assertio.client.ApiException;
import io.assertio.client.model.Check;
import io.assertio.client.model.CheckResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Get check
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkIdGetTest() throws ApiException {
        String id = null;
        Check response = api.checkIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Post check data for assertion
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkPostTest() throws ApiException {
        Check check = null;
        CheckResult response = api.checkPost(check);

        // TODO: test validations
    }
    
    /**
     * Get check
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void historyGetTest() throws ApiException {
        List<Check> response = api.historyGet();

        // TODO: test validations
    }
    
}
